services:
  backend:
    build:
      context: ./FastAPI
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/reactfastapi
    depends_on:
      - db

  frontend:
    build:
      context: ./React/finance-app
    container_name: frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reactfastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
